export default[
    {
        title : "BOAT AIRPODS PRO (BLACK)",
        category: "HEADPHONE",
        price : "200",
        image : "static/01.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_BOAT_AIRPODS_PRO_(BLACK)_₹200",
    },
    {
        title : "BOAT AIRPODS PRO (GREEN-WHITE)",
        category: "HEADPHONE",
        price : "250",
        image : "static/02.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_BOAT_AIRPODS_PRO_(GREEN-WHITE)_₹250",
    },
    {
        title : "BOAT AIRPODS PRO (RED)",
        category: "HEADPHONE",
        price : "300",
        image : "static/03.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_BOAT_AIRPODS_PRO_(RED)_₹300",
    },
    {
        title : "BOAT AIRPODS PRO (GREEN)",
        category: "HEADPHONE",
        price : "350",
        image : "static/04.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_BOAT_AIRPODS_PRO_(GREEN)_₹350",
    },
    {
        title : "BOAT AIRPODS WIRELESS (BLUE)",
        category: "HEADPHONE",
        price : "400",
        image : "static/05.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_BOAT_AIRPODS_WIRELESS_(BLUE)_₹400",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/06.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/07.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/08.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/09.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/10.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/11.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/12.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/13.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/14.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/15.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/16.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/17.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/18.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/19.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/20.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/21.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/22.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/23.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/24.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/25.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/26.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/27.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/28.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/29.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/30.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/31.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/32.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "HP GAMING VICTUS",
        category: "LAPTOP",
        price : "25,000",
        image : "static/33.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_HP_GAMING_VICTUS_₹25,000",
    },
    {
        title : "HP GAMING VICTUS PRO",
        category: "LAPTOP",
        price : "65,000",
        image : "static/34.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_HP_GAMING_VICTUS_PRO_₹65,000",
    },
    {
        title : "HP GAMING VICTUS ROG",
        category: "LAPTOP",
        price : "85,000",
        image : "static/35.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_HP_GAMING_VICTUS_ROG_₹85,000",
    },
   
    
    
]