export default[
    {
        title : "BOAT AIRPODS PRO (BLACK)",
        category: "HEADPHONE",
        price : "299",
        image : "static/01.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_BOAT_AIRPODS_PRO_(BLACK)_₹299",
    },
    {
        title : "BOAT AIRPODS PRO (GREEN-WHITE)",
        category: "HEADPHONE",
        price : "259",
        image : "static/02.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_BOAT_AIRPODS_PRO_(GREEN-WHITE)_₹259",
    },
    {
        title : "BOAT AIRPODS PRO (RED)",
        category: "HEADPHONE",
        price : "399",
        image : "static/03.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_BOAT_AIRPODS_PRO_(RED)_₹399",
    },
    {
        title : "BOAT AIRPODS PRO (GREEN)",
        category: "HEADPHONE",
        price : "359",
        image : "static/04.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_BOAT_AIRPODS_PRO_(GREEN)_₹359",
    },
    {
        title : "BOAT AIRPODS WIRELESS (BLUE)",
        category: "HEADPHONE",
        price : "499",
        image : "static/05.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_BOAT_AIRPODS_WIRELESS_(BLUE)_₹499",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/06.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/07.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/08.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/09.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/10.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/11.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/12.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/13.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/14.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "boAt New AirPods Pro",
        category: "HEADPHONE",
        price : "346",
        image : "static/15.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_sony_cx239",
    },
    {
        title : "VIVO 5G 4_128 ",
        category: "SMARTPHONE",
        price : "15,999",
        image : "static/16.webp",
        purchase :  "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_VIVO_5G_4_128_₹15,999",
    },
    {
        title : "VIVO 5G 4_128",
        category: "SMARTPHONE",
        price : "15,999",
        image : "static/17.webp",
        purchase :  "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_VIVO_5G_4_128_₹15,999",
    },
    {
        title : "VIVO 5G 4_128",
        category: "SMARTPHONE",
        price : "15,999",
        image : "static/18.webp",
        purchase :  "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_VIVO_5G_4_128_₹15,999",
    },
    {
        title : "VIVO 5G 4_128",
        category: "SMARTPHONE",
        price : "15,999",
        image : "static/19.webp",
        purchase :   "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_VIVO_5G_4_128_₹15,999",
    },
    {
        title : "VIVO 5G 4_128",
        category: "SMARTPHONE",
        price : "15,999",
        image : "static/20.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_VIVO_5G_4_128_₹15,999",
    },
    {
        title : "APPLE IPHONE 14 ",
        category: "SMARTPHONE",
        price : "79,999",
        image : "static/1.jpg",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_APPLE_IPHONE_14_₹79,999",
    },
    {
        title : "APPLE IPHONE 14 ",
        category: "SMARTPHONE",
        price : "79,999",
        image : "static/2.jpg",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_APPLE_IPHONE_14_₹79,999",
    },
    {
        title : "APPLE IPHONE 14 ",
        category: "SMARTPHONE",
        price : "79,999",
        image : "static/3.jpg",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_APPLE_IPHONE_14_₹79,999",
    },
    {
        title : "APPLE IPHONE 14 ",
        category: "SMARTPHONE",
        price : "79,999",
        image : "static/4.jpg",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_APPLE_IPHONE_14_₹79,999",
    },
    {
        title : "JBL BLUETOOTH STEREO SOUND ",
        category: "SPEAKER",
        price : "2999",
        image : "static/25.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_JBL_BLUETOOTH_STEREO_SOUND_₹2999",
    },
    {
        title : "JBL BLUETOOTH STEREO SOUND",
        category: "SPEAKER",
        price : "2999",
        image : "static/26.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_JBL_BLUETOOTH_STEREO_SOUND_₹2999",
    },
    {
        title : "JBL BLUETOOTH STEREO SOUND",
        category: "SPEAKER",
        price : "2999",
        image : "static/27.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_JBL_BLUETOOTH_STEREO_SOUND_₹2999",
    },
    {
        title : "JBL BLUETOOTH STEREO SOUND",
        category: "SPEAKER",
        price : "2999",
        image : "static/28.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_JBL_BLUETOOTH_STEREO_SOUND_₹2999",
    },
    {
        title : "REDMI NOISE FIT WITH VDO CALL",
        category: "WATCH",
        price : "4999",
        image : "static/29.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_REDMI_NOISE_FIT_WITH_VDO_CALL_₹4999",
    },
    {
        title : "REDMI NOISE FIT WITH VDO CALL",
        category: "WATCH",
        price : "4999",
        image : "static/30.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_REDMI_NOISE_FIT_WITH_VDO_CALL_₹4999",
    },
    {
        title : "REDMI NOISE FIT WITH VDO CALL",
        category: "WATCH",
        price : "4999",
        image : "static/31.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_REDMI_NOISE_FIT_WITH_VDO_CALL_₹4999",
    },
    {
        title : "REDMI NOISE FIT WITH VDO CALL",
        category: "WATCH",
        price : "4999",
        image : "static/32.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_REDMI_NOISE_FIT_WITH_VDO_CALL_₹4999",
    },
    {
        title : "HP GAMING VICTUS",
        category: "LAPTOP",
        price : "25,999",
        image : "static/33.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_HP_GAMING_VICTUS_₹25,999",
    },
    {
        title : "HP GAMING VICTUS PRO",
        category: "LAPTOP",
        price : "65,999",
        image : "static/34.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_HP_GAMING_VICTUS_PRO_₹65,999",
    },
    {
        title : "HP GAMING VICTUS ROG",
        category: "LAPTOP",
        price : "85,999",
        image : "static/35.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_HP_GAMING_VICTUS_ROG_₹85,999",
    },
    {
        title : "DELL G15 I5 12 GEN",
        category: "LAPTOP",
        price : "95,999",
        image : "static/36.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_DELL_G15_I5_12_GEN_₹95,999",
    },
    {
        title : "DELL G15 I5 12 GEN",
        category: "LAPTOP",
        price : "95,999",
        image : "static/37.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_DELL_G15_I5_12_GEN_₹95,999",
    },
    {
        title : "DELL G15 I5 12 GEN",
        category: "LAPTOP",
        price : "95,999",
        image : "static/38.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_DELL_G15_I5_12_GEN_₹95,999",
    },
    {
        title : "DELL G15 I5 12 GEN",
        category: "LAPTOP",
        price : "95,999",
        image : "static/39.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_DELL_G15_I5_12_GEN_₹95,999",
    },
    {
        title : "DELL G15 I5 12 GEN",
        category: "LAPTOP",
        price : "95,999",
        image : "static/40.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_DELL_G15_I5_12_GEN_₹95,999",
    },
    {
        title : "LENOVO IDEAPAD GAMING I5 11 GEN",
        category: "LAPTOP",
        price : "55,999",
        image : "static/41.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_LENOVO_IDEAPAD_GAMING_I5_11_GEN_₹55,999",
    },
    {
        title : "LENOVO IDEAPAD GAMING I5 11 GEN",
        category: "LAPTOP",
        price : "55,999",
        image : "static/42.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_LENOVO_IDEAPAD_GAMING_I5_11_GEN_₹55,999",
    },
    {
        title : "LENOVO IDEAPAD GAMING I5 11 GEN",
        category: "LAPTOP",
        price : "55,999",
        image : "static/43.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_LENOVO_IDEAPAD_GAMING_I5_11_GEN_₹55,999",
    },
    {
        title : "LENOVO IDEAPAD GAMING I5 11 GEN",
        category: "LAPTOP",
        price : "55,999",
        image : "static/44.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_LENOVO_IDEAPAD_GAMING_I5_11_GEN_₹55,999",
    },
    {
        title : "LENOVO IDEAPAD GAMING I5 11 GEN",
        category: "LAPTOP",
        price : "55,999",
        image : "static/45.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_LENOVO_IDEAPAD_GAMING_I5_11_GEN_₹55,999",
    },
    {
        title : "LG 32 INCH LED SMART TV",
        category: "TV",
        price : "35,999",
        image : "static/46.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_LG_32_INCH_LED_SMART_TV_₹35,999",
    },
    {
        title : "REALME 32 INCH SMART Android TV",
        category: "TV",
        price : "15,999",
        image : "static/47.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_REALME_32_INCH_SMART_Android_TV_₹15,999",
    },
    {
        title : "ONEPLUS Y1S 43 INCH SMART Android TV",
        category: "TV",
        price : "19,999",
        image : "static/48.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_ONEPLUS_Y1S_43_INCH_SMART_Android_TV_₹19,999",
    },
    {
        title : "MI 32 INCH SMART GOOGLE TV",
        category: "TV",
        price : "29,999",
        image : "static/49.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_MI_32_INCH_SMART_GOOGLE_TV_₹29,999",
    },
    {
        title : "SAMSUNG CRYSTAL SMART TIZEN TV",
        category: "TV",
        price : "39,999",
        image : "static/50.webp",
        purchase : "https://api.whatsapp.com/send?phone=919679432975&text=i_want_to_buy_SAMSUNG_CRYSTAL_SMART_TIZEN_TV_₹39,999",
    },
    
    
]